#!/bin/bash
# This script is used to run git commands in the gost-git container

CONTAINER=gost-git

# Проверяем, запущен ли контейнер
if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
  echo "error: ${CONTAINER} not running."
  echo "run 'start' first."
  exit 1
fi

docker exec -i -w /workspace "${CONTAINER}" git "$@"
